### ISSUE TITLE
Use the EditorFileDialog instead of FileDialog

### ISSUE THREAD

**Issue by poohcom1** [viniciusgerevini/godot-aseprite-wizard#102]
Godot has an enhanced version of `FileDialog` called [`EditorFileDialog`](https://docs.godotengine.org/en/stable/classes/class_editorfiledialog.html), which offers a lot more features. This would make file navigation when choosing Aseprite files or output directories much more pleasant. I'm wondering if there were limitations that required `FileDialog` to be used, or was EditorFileDialog just never considered?

**Comment by viniciusgerevini** [comment]
Thanks for raising this. No limitations. I just likely never came across it. I think in older versions the differences were not clearly stated and I never checked. This should be a quick win.

I'll be working on the drag-and-drop support in the docks soon and I can bundle this change together. Unless you already have something or want to do it yourself. Thanks

**Comment by poohcom1** [comment]
Thanks!

**Comment by viniciusgerevini** [comment]
Thank you for the suggestion. I'll include it in the next version I'll be releasing soon. I'm just polishing some changes in the automatic importer before. Cheers
