### ISSUE TITLE
Command not found on Mac 

### ISSUE THREAD

**Issue by Wardius** [viniciusgerevini/godot-aseprite-wizard#107]
I tried multiple options for the Aseprite command path on MacOS but it always says "Command not found"
The same project works perfectly fine on Windows.

I tried using the path provided by Steam and the one in the Applications folder:
"/Users/username/Library/Application Support/Steam/steamapps/common/Aseprite/Aseprite.app"
"/Users/username/Applications/Aseprite.app"

I am using Godot 4.1.2.stable and MacOS Sonoma 14.0

**Comment by viniciusgerevini** [comment]
Hello. In MacOS, Aseprite.app is actually a folder and the actual executable is inside. There is an example in the Readme. For the path you wrote I reckon it should be:

`/Users/username/Library/Application Support/Steam/steamapps/common/Aseprite/Aseprite.app/Contents/MacOS/aseprite`

**Comment by Wardius** [comment]
You're right! I thought I had tried that as well.
It works perfectly now. Thank you (and especially thanks to your work with this plugin, I use it constantly and it saves soooo much time and effort!)

**Comment by Wardius** [comment]
By the way, I looked for a readme file but could not find it. I downloaded your plugin via the Asset Browser in Godot; maybe that's why?

**Comment by viniciusgerevini** [comment]
Thank you! I'm glad it's been useful.

Good call out about the README. It currently lives in the root folder, which I do not include in the export so it won't be part of the exported zip. I'll find a way to include it in the right addon folder. Cheers
