### ISSUE TITLE
Possibility to import sprites without an AnimationPlayer in the inspector

### ISSUE THREAD

**Issue by jefvel** [viniciusgerevini/godot-aseprite-wizard#113]
Hello!
I was wondering if it would be possible to import Aseprite files without having to add an AnimationPlayer when importing through the inspector? I have a lot of sprites that contain a single frame, and the possibility to skip creating AnimationPlayers for them would be neat.

Thanks!

**Comment by viniciusgerevini** [comment]
Hello @jefvel . I'll take a look into it this week. It's definitely possible, I just need to think a bit to not over complicate things.

**Comment by viniciusgerevini** [comment]
I forgot to close this issue. This was released on version `7.1.0`. Cheers

**Comment by jefvel** [comment]
Thanks a lot!!!
