### ISSUE TITLE
"InspectorDock" shadows a native class Godot 3.6 beta4

### ISSUE THREAD

**Issue by dannygaray60** [viniciusgerevini/godot-aseprite-wizard#120]
I found this error when using the latest version of the plugin (6.2) in godot 3.6 beta4. It seems that it is just a name conflict with some new native class, resolved by changing the name. I know that godot 3.6 is not stable yet but I am reporting the error in case you want to prevent it

![Screenshot 2024-01-25 085945](https://github.com/viniciusgerevini/godot-aseprite-wizard/assets/30391210/56287cc6-8b5b-4ce4-8394-7d80bac4670c)

**Comment by viniciusgerevini** [comment]
Hey @dannygaray60 thanks a lot for reporting this. I'll fix this. Lesson learned. I shouldn't have set such a generic name haha. Cheers

**Comment by dannygaray60** [comment]
No problem! Thank you for your addon! :3

**Comment by viniciusgerevini** [comment]
Included in the latest release (6.3.0 Godot 3). Already available in the branch and release page. It takes a few days for it to be available in Godot's asset lib. Cheers.
