### ISSUE TITLE
make import defaults affect the import settings in `Sprite2D` props

### ISSUE THREAD

**Issue by jefvel** [viniciusgerevini/godot-aseprite-wizard#121]
Currently if I select "only visible layers" in the aseprite importer default settings, it'll still be disabled in this menu: 
![image](https://github.com/viniciusgerevini/godot-aseprite-wizard/assets/494817/a36a2cda-1a04-45db-859b-92fd16fa3bf5)

It'd be nice if there was a way to configure the default settings of the options there. Or maybe there is one and I've missed it?

**Comment by viniciusgerevini** [comment]
Yeah, I don't think there is a default option for that. That was deliberate as I wouldn't recommend relying too much on that option. But each person has a different pipeline, so I guess there is no harm on adding the default settings. It's a straight forward change. I'll add it to the next release. Thanks.

**Comment by viniciusgerevini** [comment]
Included in the latest release (7.2.0 Godot 4, 6.3.0 Godot 3). Already available in the branch and release page. It takes a few days for it to be available in Godot's asset lib. Cheers.
