### ISSUE TITLE
Forward slash in imported animation name can't be renamed

### ISSUE THREAD

**Issue by david-drew** [viniciusgerevini/godot-aseprite-wizard#130]
I'm using a file from an artist who used "L/R" for left-right animations.  After import, I wanted to make the names consistent, and started renaming them, only to find that godot treats the "/" as a separator and only changes the substring that follows the "/".
It's a minor issue, since you can just edit the aseprite file itself, but it would be nice to have special characters be substituted on import.

**Comment by viniciusgerevini** [comment]
Hello @david-drew . Thanks for reaching out. This is a feature actually. Godot 4 supports animation libraries and `/`  is the character used to separate the library name from the animation name. You can still rename the first part by editing the library name, but as you mentioned that was supposed to be just the animation name and you probably don't want a library.

If we escape the separator we lose the ability of allowing users to define libraries via Aseprite. Allowing changing the separator or escaping it would probably be confusing, given Godot uses the format in a few methods. From the docs:

> Some methods and properties use a single key to reference an animation directly. These keys are formatted as the key for the library, followed by a forward slash, then the key for the animation within the library, for example "movement/run"

https://docs.godotengine.org/en/stable/classes/class_animationplayer.html#class-animationplayer
