### ISSUE TITLE
Outdated message displayed when Aseprite command could not be executed

### ISSUE THREAD

**Issue by sandord** [viniciusgerevini/godot-aseprite-wizard#136]
When the Aseprite command could not be executed, a message is displayed:

    Aseprite command failed. Please, check if the right command is in your PATH or configured through
    "Project > Tools > Aseprite Wizard Config"

However, this location is outdated and should point to the actual location instead:

    Editor -> Editor Settings -> Aseprite -> General -> Command Path

**Comment by sandord** [comment]
I could create a PR if you want.

**Comment by viniciusgerevini** [comment]
Thanks @sandord . I noticed this message some time ago, but as my intention is to make the Aseprite Wizard Config path field editable again in a newer version I didn't change it. 

As that's the place where the command can be tested it's a bit annoying to have to switch back and forth between the dialog and the editor settings. But I'm not sure when I will get to it, so feel free to raise a PR if you wish. Cheers.

**Comment by sandord** [comment]
Here's the PR: https://github.com/viniciusgerevini/godot-aseprite-wizard/pull/138

**Comment by viniciusgerevini** [comment]
Thank you
