### ISSUE TITLE
Texutre filter should be an option instead of only overwriting to "nearest" by default

### ISSUE THREAD

**Issue by MichailIoannou** [viniciusgerevini/godot-aseprite-wizard#143]
Aseprite wizard will overwrite texture filter from "inherit" to "nearest" by default. I am no expert but if you are making pixelart you set your project texture filter to Nearest and then everything inherits that, depending on how godot handles an overwrite it might be best not to redefine that option for every sprite imported by this tool.

**Comment by viniciusgerevini** [comment]
Hi, I don't think this is an issue to justify one more config. The overwrite is transparent to the node and not setting it might bring issues later. For example, if someone starts the project with "nearest" by default and then decides they want high res for the interface, they would have to go to every import and set the filter to "nearest". I can't think on a scenario where not having the filter is desirable.
