### ISSUE TITLE
Changes to import fields on a node are discarded when navigating away without clicking Import

### ISSUE THREAD

**Issue by sandord** [viniciusgerevini/godot-aseprite-wizard#145]
So when I enter an "Output File Name" for example and click on another node and then navigate back to the initial node, the change is gone.

**Comment by viniciusgerevini** [comment]
Oh, good catch. Yes, it's indeed not persisting it. I think before it would persist when expanding and collapsing the options section but I removed that when refactoring because it would have partial settings that wouldn't work in the import tab. I will bring it back in a smarter way. Thanks
