### ISSUE TITLE
Confusing behavior of Output File Name field

### ISSUE THREAD

**Issue by sandord** [viniciusgerevini/godot-aseprite-wizard#146]
The *Output File Name* field is used as a prefix but the name of the property is a little confusing given its behavior.

I'd suggest *Output File Name Prefix* or something but I can understand breaking compatibility is not worth it at this point.

**Comment by viniciusgerevini** [comment]
Yes, that's a good point. It works as a prefix when a layer is selected, but as the full name when not. 

I reckon I can change the label without changing the property or persisted data and that should be backwards compatible.
