### ISSUE TITLE
Aseprite command failed. Please, check if the right command is in your PATH or configured through "Editor > Editor Settings > Aseprite > General > Command Path".

### ISSUE THREAD

**Issue by BlixSlic** [viniciusgerevini/godot-aseprite-wizard#149]
does anyone know how i can fix it because i don't know what command i need to put in the PATH

**Comment by blubberdiblub** [comment]
@BoodyZedan 
If you're on Windows, you need to put the full path (including drive letter) to the aseprite.exe there.

You can for instance do it by finding the exe on your system (either wherever you installed it or if you're using the Steam version it's probably inside `C:\Program Files (x86)\steam\steamapps\common\Aseprite`), right click it and choose `Copy as path`.

Then paste it into the Aseprite Command Path field in the Editor Settings.

:warning: And then you also need to **remove the double quotes** from the beginning and end of the path, as it would consider them part of the path, which they aren't.

![image](https://github.com/viniciusgerevini/godot-aseprite-wizard/assets/69097/26b1760b-eb14-45e2-a9fa-0c1780bb75ca)
