### ISSUE TITLE
improvement suggestion: print on start and on import about aseprite not found on path

### ISSUE THREAD

**Issue by Gnumaru** [viniciusgerevini/godot-aseprite-wizard#153]
I have just reinstalled my OS and forgot to put the aseprite directory in the executable path. When I noticed that my imports were not working I just remembered that I forgot to put the aseprite directory in the executable path.

Some people may have a similar problem, or maybe some people may just install the extension for the first time without reading the readme and later complaing about the extension not working. So it would be usefull if, uppon extension load and uppon each import, if the aseprite executable cannot be find in the executable path, then a warning (or even an error) is printed stating something like "the aseprite executable could not be found in the executable path. Nothing will be imported."

**Comment by viniciusgerevini** [comment]
Thank you. Will do. It sound like a good improvement. Cheers

**Comment by viniciusgerevini** [comment]
Hello. I just confirmed a warning is already given in these cases:

![Screenshot from 2024-06-28 09-06-23](https://github.com/viniciusgerevini/godot-aseprite-wizard/assets/4930052/bc85088b-8e6a-4cf9-9a38-fcadfc849589)

I also implemented OS based default command selection on #154 , which might make it more likely the right command will be used from the start.
