### ISSUE TITLE
Add option to turn off adding visible keyframes on animation

### ISSUE THREAD

**Issue by cwchunwei** [viniciusgerevini/godot-aseprite-wizard#158]
Love your plugin!

One issue that I'm running into right now is that everytime I import the animation, the 'visible' property of the sprite gets keyed in the AnimationPlayer.

I understand that this is likely a feature.
My use case is that I would like to drive the visible property in code, let's say for an attachment to the player. But right now everytime I update the animation, I would need to turn delete the 'visible' track in the AnimationPlayer for each individual component I have, which is slowly adding up time spent to delete them.

I assume that this would be an easy fix, but let me know if it's actually otherwise! Thank you!

**Comment by viniciusgerevini** [comment]
Hey @cwchunwei . Thanks for reporting this. Yeah, this is related to the "hide unused sprites" feature, but I don't think that is implemented correctly. I'll have to think on a better way to go about this track, but in the meantime, assuming you don't use this feature, you can remove it locally by commenting this line https://github.com/viniciusgerevini/godot-aseprite-wizard/blob/godot_4/addons/AsepriteWizard/creators/animation_player/animation_creator.gd#L104

Hopefully that unblocks you until I get to fix this. Cheers.

**Comment by viniciusgerevini** [comment]
Fixed on version 8.0.0
