### ISSUE TITLE
animation tag with  _  (the exception prefix) are not being imported

### ISSUE THREAD

**Issue by erniel** [viniciusgerevini/godot-aseprite-wizard#164]
the title explains for itself. i encountered this issue on version 8.0.0. so i just reverted it back to the previous version 7.5. 

it works though if you set the tag properties repeat to 1 but i dont want o edit all my aseprite file again

**Comment by viniciusgerevini** [comment]
Thanks @erniel . Indeed I can see the issue when importing using AnimationPlayers. I'm looking into it.

**Comment by viniciusgerevini** [comment]
I think I found the issue. For context, in the latest release I fixed the logic to cleanup empty animations, however I forgot that for the old loop prefix feature I remove the prefix when including the animation, so the _animation wouldn't match with animation. It should be a simple fix.

**Comment by viniciusgerevini** [comment]
Fix included in version 8.0.1. Usually it takes a few days for it to be published to the Godot Asset Lib, but it's already available on the main branch and releases. I hope this didn't cause too much trouble for you. Thanks for reporting it.
Cheers.
