### ISSUE TITLE
Importing file into a new unsaved scene error

### ISSUE THREAD

**Issue by JamesPeters98** [viniciusgerevini/godot-aseprite-wizard#169]
If you try to import an Aseprite file onto an AnimatedSprite2D that has just been added to a new unsaved (unamed) Scene, it will give the following error:

`aseprite generated bad data file`

Presumably this is due to the output folder default being set to [Same as scene] which doesn't exist yet.

**Comment by viniciusgerevini** [comment]
Thanks James. yeah, that's definitely it. I reckon the simplest fix will be to notify the user if the scene has not been saved and no output is selected. I'll ship this in the next version. Cheers.
