### ISSUE TITLE
Option for don't create  SpriteFrames Resource (.res) file

### ISSUE THREAD

**Issue by SyliawDeV** [viniciusgerevini/godot-aseprite-wizard#20]
### **Hi, Vini..**

First your plugin is great for me to manager spritesheet. I really like the option Split Layer to Multiple Resource. Currently I only want it to import the png(and .json) but not create extra SpriteFrames(.res). Because I use Animation PLayer with another Plugin that take the .json file of layer.

Second, yep I could just delete the .res file after import but could take time to select .res file and delete it. Can you make a quick option for it. I tried to run into plugin but seem like could not fully understand it( Sorry I don't good at plugin)

### Thanks for your great work.
![image](https://user-images.githubusercontent.com/66520542/115132215-3b5cb700-a028-11eb-9202-c6c3ac38265e.png)

**Comment by viniciusgerevini** [comment]
Hello @SyliawDeV,
I'm glad the plugin is useful for you. I believe this option fits well the wizard screen and it shouldn't take much to implement it.
I'll take a look and let you know. Thanks for the suggestion.

**Comment by viniciusgerevini** [comment]
Hi @SyliawDeV . The feature was included in version 1.3.0. It's already on the main branch and the asset library.
Thanks :)

**Comment by SyliawDeV** [comment]
Thanks @viniciusgerevini, version 1.3.0 work like charm and your work on plugin too.

**Comment by viniciusgerevini** [comment]
Thanks @SyliawDeV , and thanks for contributing to the project :+1:
