### ISSUE TITLE
Needs finer grained auto-import option

### ISSUE THREAD

**Issue by furroy** [viniciusgerevini/godot-aseprite-wizard#23]
I have many aseprite files in my project, but sometimes they need to be exported in a special way. So either I enable the auto-import option and it breaks those files, or I leave it disabled and inevitably forget to re-import some files.  

It would be super useful if there was some mechanism by which you could tell it which files to auto import and/or which to skip.  Maybe by putting them in subfolders called "auto import" or "skip import" or any scheme really where I can set it up one time and not have to fuss with it after that.

**Comment by viniciusgerevini** [comment]
Hello @furroy . Thanks for the suggestion. In fact, you can already do something like this by using Godot's `.gdignore`.
From the docs:
> To prevent Godot from importing files contained in a specific folder, create an empty file called .gdignore in the folder (the leading . is required).
https://docs.godotengine.org/en/stable/getting_started/workflow/project_setup/project_organization.html

With that you should be able to create a "skip import" folder that will never be imported.
