### ISSUE TITLE
Imported an aesprite file, and completely corrupted my project

### ISSUE THREAD

**Issue by jay11800** [viniciusgerevini/godot-aseprite-wizard#24]
when I imported a file with the aesprite wizard, it crashed godot, and then corrupted my project, removing all project settings I had set up, and even somehow all the godot editor settings i had as well. How can it mess up so badly >:(

**Comment by viniciusgerevini** [comment]
I see. Sorry about your project. Can you give me some more information? Which Godot and Aseprite version are you using? Which operational system? Does it happen on every import?

**Comment by jay11800** [comment]
Godot 3.3 Stable, and for Aesprite I'm using 1.2.27, Windows 10, and it seems like it was just with that one import, when I selected reimport in the editor. I'm now just going to stick with Project > Tools > Asprite wizard as that seems to work just fine.

Thankfully it was just config files that got super corrupted, I was able to recover and backup all code and scenes
