### ISSUE TITLE
Does not seem to work with Steam

### ISSUE THREAD

**Issue by erayerdin** [viniciusgerevini/godot-aseprite-wizard#27]
I have Godot and Aseprite installed with my Steam.

Installed the plugin, restarted it, it didn't work. So I thought "It's probably about the path issue.". So I actually added `aseprite` binary path to my `PATH` variable. It doesn't work again, saying:

<details>
<summary>In-Godot Logs</summary>

```
ERROR - Could not import aseprite file: Aseprite command failed. Please, check if the right command is in your PATH or configured through the "configuration" button.
 editor/editor_file_system.cpp:1817 - Error importing 'res://protagonist.aseprite'
```
</details>

<details>
<summary>Environment</summary>

 - Ubuntu 20.04
 - Steam 162...086
 - Godot Engine v3.3.2.stable.official
 - Aseprite v1.2.27-x64
</details>

Aseprite is in `PATH` variable. I checked that. I also tried restarting Godot and Steam as well. It didn't work.

**Comment by viniciusgerevini** [comment]
Are you able to use `aseprite` from your terminal?

I haven't used Steam's Aseprite on linux, but I guess as long the path is right it should work. I'll have to install it to give it a try. Do you mind telling me what is the path to the binary you added to your PATH?

**Comment by viniciusgerevini** [comment]
Also, you should be able to use the path to Aseprite's binary directly in the configuration screen. It may not be what you are looking for but it is a workaround so you can use the plugin in the meantime.

**Comment by erayerdin** [comment]
Seems like rebooting the computer has done the trick. It's resolved in my case. Feel free to close.

**Comment by viniciusgerevini** [comment]
Nice! Thanks for letting me know.
