### ISSUE TITLE
Wrong Tooltip

### ISSUE THREAD

**Issue by imsamuka** [viniciusgerevini/godot-aseprite-wizard#28]
In the "Aseprite Wizard" window, the `Do not create resource file` checkbox, have the following tooltip: `Removes borders from sprites/layers before saving them.` which is the same as the checkbox above.

Also, in the same window, both `Configuration` and `Close` buttons are both uncapitalized.

I thought about doing a pull request solving both problems, but actually I don't know exactly the function of that checkbox. The name leads me to think it's a pointless feature, so I guess it's not so obvious what it really does.

**Comment by viniciusgerevini** [comment]
Thanks @imsamuka . copypasta issue.

This option was a feature request. Some people use the plugin to get just the `.json` and `.png` files. In those cases they don't need the resource file to be created. The README has the right tooltip:

> Does not create SpriteFrames resource. Useful if you are only interested on the .json and .png output from Aseprite.

**Comment by imsamuka** [comment]
Messing up with the plugins got me to use this feature in the end. I'm very glad that it exists hahah.

**Comment by viniciusgerevini** [comment]
lol feel free to open the PR with the changes you suggested, otherwise I'll fix it over the weekend. Thanks.

**Comment by imsamuka** [comment]
I did the PR and with another fix. I don't know how to link this issue to the PR and if it does something, so I will close the issue now, thanks!
