### ISSUE TITLE
Copyright Question

### ISSUE THREAD

**Issue by imsamuka** [viniciusgerevini/godot-aseprite-wizard#29]
Excuse me, but i'm just starting with open source contribution, so i'm not used to how Issues, Pull Requests and discussions should behave. I don't know if I should create a issue to discuss this with you, but i created one on the doubt.

I created a [fork](https://github.com/imsamuka/aseprite_importer) of another Godot plugin, and I copied over the [aseprite_cmd.gd](https://github.com/viniciusgerevini/godot-aseprite-wizard/blob/master/addons/AsepriteWizard/aseprite_cmd.gd) from this repository, to implement a option to import `.aseprite` files directly (Without needing to manually generate .json files).

I should copy the license here over too?
And credit you in the `README.md`?
There's another thing I should take note about?

I'm Sorry if i seem rude.

**Comment by viniciusgerevini** [comment]
Hello @imsamuka . That's alright. You can open issues whenever you have question or doubts.

So, regarding LICENSE stuff. If you are copying the full file it is good practice to put the [LICENSE](https://github.com/viniciusgerevini/godot-aseprite-wizard/blob/master/LICENSE) notice from this repo as a comment in the beginning of the file. This could also be helpful in case people wants to look for the source in the future.

However, keep in mind the other maintainer may not want this file copied to his project, as it does more than what he needs. Maybe open an issue on his project before starting working on it.

If you decide to copy only pieces from it or just use it as inspiration there is no need to add any reference in your work. A shout is always appreciated, but it is totally up to you.

Thanks for asking. Good luck.

**Comment by imsamuka** [comment]
Thank you for the answer. I will put the LICENSE as a comment.

I started working on it before asking, so at this point it is already working very well. Regards to the file containing more than it needs to be, some of the features can be implemented as options in the future (for example **export_mode**, **exception_pattern**, **only_visible_layers**, **trim_images**) the same way I implemented the **aseprite_command** option, so I am not exactly comfortable removing unused parts now...

But I can probably remove the part which creates the resource AnimatedSprite uses, as it is useless there, and there's your plugin to generate those.
