### ISSUE TITLE
Doesn't work with Animation Player

### ISSUE THREAD

**Issue by furroy** [viniciusgerevini/godot-aseprite-wizard#37]
This plugin works great if you are using an AnimatedSprite, you can just drop the generated .res file right into it.  But if you have a normal Sprite and use an AnimationPlayer/AnimationTree, to control it, there's no way I could find to get the frame animations loaded into the player.

I don't expect this to be fixed, but there is a different Aseprite Importer that does do this in case anyone else is stuck with this issue like I was:  https://github.com/hectorid/aseprite_importer

**Comment by viniciusgerevini** [comment]
Thanks @furroy . That's correct. The scope of this plugin is AnimatedSprites only, and by including AnimationPlayer I would be just reimplementing something that already exists in the plugin you linked.

Some people do use aseprite-wizard in conjunction with this other plugin though. In fact, the option to not generate the resource was requested exactly for this use-case. You can use aseprite-wizard to generated the spritesheet and json, and use the other importer to transform it into an AnimationPlayer.

**Comment by TheOrioli** [comment]
> One thing I'm curious is what is the benefit of using AnimationPlayer instead of AnimatedSprites? I mean, I know what's the use case for using AnimationPlayers, but in the context of Aseprite importing, what does it provide that a simple AnimatedSprite doesn't?

I can only speak for my use case, but the key benefit is being able to sync other animations to the sprite animation easily. In my example, I'm triggering sound effects, particles and collisions. 
Currently the AnimationPlayer animation track can control and play other AnimationPlayer's animations and show their duration, but it cannot do the same for an AnimatedSprite.

**Comment by viniciusgerevini** [comment]
Thanks @TheOrioli . It makes sense. That's also the use case I know. I guess the only way to achieve a similar behavior would be using AnimatedSprite's signals, but that sure add complexity and it's not as straight forward.

I'll give AnimationPlayer a try in the coming weeks, but the structure is very different from SpriteFrames, so it might be the case it doesn't fit this plugin. I was with the impression that the other importer linked here already did the trick, but by looking in their README it seems there is still a fair amount of manual process involved.

I'll let you know when I have some progress.

**Comment by TheOrioli** [comment]
I've made a plugin of my own now https://github.com/KikimoraGames/godot_animationplayer_spriteframes_helper specifically to help me out with adding SpriteFrames data to an AnimationPlayer. 
It should be possible to use the existing SpriteFrames you generate and create animations that can be imported into an AnimationPlayer. The only limitation would be that the users would need to use an AnimatedSprite, since I'm not sure you can easily access the internal SpriteFrames AtlasTexture to use in a regular Sprite node.

**Comment by tavurth** [comment]
+1 for this, my purpose would be to use the `AnimationTree` which currently relies on having the animations setup individually in an `AnimationPlayer`.

**Comment by viniciusgerevini** [comment]
Heyo! I implemented this as a new feature in #44 . Feel free to pick the code from the branch `animation_player_support` to test it yourselves if you wish.

**Comment by viniciusgerevini** [comment]
Alright! This feature is available now in Godot's asset library on Aseprite Wizard version 4.0.0. Thanks for your suggestions and contributions.
