### ISSUE TITLE
Solved: Issue getting it to work on windows when Path does not work

### ISSUE THREAD

**Issue by creadicted** [viniciusgerevini/godot-aseprite-wizard#41]
Hello. 
I added Aseprite to my local path. The normal installation and after this did not work, the steam version path. 
I tested it with the folder and the path

```
'G:\SteamLibrary\steamapps\common\Aseprite'
'G:\SteamLibrary\steamapps\common\Aseprite\Aseprite.exe'
```
What did the trick at the end was to place the **full path** to the `Aseprite Command Path` 

![image](https://user-images.githubusercontent.com/1899013/143763517-b287524b-32d8-4e2c-a33e-37f00e797e5c.png)

I leave this here for others that have issues with windows.

**Comment by viniciusgerevini** [comment]
Thanks @creadicted . Someone notified some weirdness around windows path and Godot before #26 . Unfortunately, they also couldn't find the reason for that.

**Comment by viniciusgerevini** [comment]
I added this as a note to the path section in the README.md. Thanks.
