### ISSUE TITLE
Weird Editor Description

### ISSUE THREAD

**Issue by Justiniscoding** [viniciusgerevini/godot-aseprite-wizard#50]
I don't think this is a bug, but whenever I import an aseprite file in godot it gives my sprite a node description. An example one I got after importing a file is:
```
YXNlcHJpdGVfd2l6YXJkX2NvbmZpZwpzb3VyY2V8PXJlczovL0FydC9Ub3JjaC5hc2Vwcml0ZQpsYXllcnw9Cm9wX2V4cHw9RmFsc2UKb19mb2xkZXJ8PQpvX25hbWV8PQpvbmx5X3Zpc2libGV8PUZhbHNlCm9fZXhfcHw9Cg==
```
Is there a reason this happens? If not, how could I prevent this?

**Comment by viniciusgerevini** [comment]
Hello @Justiniscoding . This is explained in the [FAQ](https://github.com/viniciusgerevini/godot-aseprite-wizard#what-is-the-gibberish-in-the-nodes-editor-description) section in the README.

This is where the plugin stores data for future imports. You can delete it afterwards, but you would have to re-fill all the fields when re-importing. The readme explains the reasoning behind it. Unfortunately, there is no workaround.

**Comment by Justiniscoding** [comment]
Oh, I never read the FAQ. I'll close this for now
