### ISSUE TITLE
Sprite3D

### ISSUE THREAD

**Issue by Remixful** [viniciusgerevini/godot-aseprite-wizard#53]
Is it possible to get this to work with Sprite3D?

**Comment by viniciusgerevini** [comment]
It seems possible. I'll try it tomorrow and release it if it works. The flow should be the same as using an AnimationPlayer with a Sprite2D. Thanks for the suggestion

**Comment by viniciusgerevini** [comment]
@Remixful just an update. I've tried re-using the code for `Sprite3D`, but even though the import succeeds, the console get stuck with an error message and it's not clear to me why.
```
 editor/import/resource_importer_texture.cpp:96 - Condition "err != OK" is true. Continuing.
```
I'll look into this issue as soon I get the time to do so. Once this is solved, it should also be simple enough to implement for `AnimatedSprite3D` as well.
