### ISSUE TITLE
How to use aseprite wizard plugin via script?

### ISSUE THREAD

**Issue by hutomosaleh** [viniciusgerevini/godot-aseprite-wizard#54]
Is it possible to use the plugin via script? I'd like to i.e. dynamically load .aseprite file and import it to my node

**Comment by viniciusgerevini** [comment]
Hello @hutomosaleh . This is not possible with this plugin as is. This would require Aseprite to be present in the machine the game/application is being executed or have it embedded in the app, which doesn't seem like a good idea.

Also, the plugin relies on the `EditorFileSystem` to trigger scan and import the resources properly. However, this could be worked around.
