### ISSUE TITLE
Config file lives outside version control

### ISSUE THREAD

**Issue by TheOrioli** [viniciusgerevini/godot-aseprite-wizard#56]
The config file is currently stored in the `user://` folder, which means that it cannot be version controlled. This becomes an issue when using the AsepriteWizard in cloud builds in case of any setting changes that need to be persisted. 

For example, if the game requires the Aseprite Importer, the exported build will fail "successfully" because it simply will not perform an import of the `.aseprite` files. This will then cause a silent crash of the exported build on startup.

My suggestion is to move the settings from the `user://` folder into the godot project settings and the editor settings.

The only setting that is machine specific among all the ones I see here is the `Aseprite Command Path`, all the other ones are project specific.
![image](https://user-images.githubusercontent.com/2500134/179737455-2e76c7e4-42af-456d-9d47-8863d018ec7f.png)

This would work in a similar way to the import preset storage in #55

**Comment by viniciusgerevini** [comment]
That's a good point. Yeah, this config started with the Aseprite Command Path only, that's why it's outside the Project Settings. At first, I was considering all these configs as global, but now thinking again you are right, they are actually project specific.

I think we should be able to move all configs, but the Aseprite Command Path, to the Project Settings. The Command Path will become kind of an outlier, but that's ok.

**Comment by viniciusgerevini** [comment]
I'm working on this one now. I just realised I can keep the Aseprite Command Path in the `EditorSettings`. I might not even need a config dialog anymore. The only downside is that I would lose the test button, but I'm checking what can be done.

**Comment by viniciusgerevini** [comment]
I started working on this one and I just realised what you meant by EditorSettings. I can keep the Aseprite Command Path there and I wouldn't need a config dialog anymore. The only downside is that I would lose the test button, but I'm checking what can be done about it.
