### ISSUE TITLE
It stopped working all of a sudden

### ISSUE THREAD

**Issue by cpodgell** [viniciusgerevini/godot-aseprite-wizard#57]
I have used this in the past and it worked perfectly fine.  However, recently, in all my projects it doesn't do anything when I click import.

I'm not sure if it's becuase of an update to asesprite?  But nothing has changed (to my knowledge).

I can load animation player fine, I can load the .ase sprite fine, but the layers drop down does not represent what I see in asesprite.
When I click Import - nothing happens.

**Comment by cpodgell** [comment]
I realized it was an aseprite issue

**Comment by cpodgell** [comment]
closed

**Comment by viniciusgerevini** [comment]
Thanks @cpodgell . I'll check if there is any improvement to be done on the feedback given by the plugin in case the aseprite command misbehaves
