### ISSUE TITLE
Aseprite command path invalid

### ISSUE THREAD

**Issue by garryheart** [viniciusgerevini/godot-aseprite-wizard#60]
command path is right then also it's showing command not found. my aesprite version is v1.2.39. is the addon not compatible with this version of aseprite.

![image](https://user-images.githubusercontent.com/110745210/183266840-be8776a3-4f9b-455d-a322-82df22a1c782.png)

![image](https://user-images.githubusercontent.com/110745210/183266875-c39d2c3a-944c-4667-a599-b15ac8edf333.png)

**Comment by viniciusgerevini** [comment]
Your two screenshots show different paths. The bottom one has an extra `Program Files (x86)` on it. That's likely the missing part.

**Comment by garryheart** [comment]
Thank you very much it's working now.☺️ I was really confused. Thanks a lot.
