### ISSUE TITLE
Groups imported as layers

### ISSUE THREAD

**Issue by boruok** [viniciusgerevini/godot-aseprite-wizard#69]
**version:**
aseprite: v1.3-beta21-x64
godot: v3.6.beta.custom_build [0803b4168]

**problem:**
Hello, looks like `group` in `.ase` imported as another `layer` which is unnecessary texture dublication.

**steps to reproduce:**
1. create ase file with following structure
```
- group
 - layer1
 - layer2
```
2. setup aseprite wizard settings input/output
3. check `Split layers in multiple resources` option
4. press import button

output will be:
```
group.png (dublicate of layer1)
layer1.png
layer2.png
```

**possible solutions:**
1. follow aseprite folders as folders in project
2. ignore folders
3. use folder name as prefix to each file

**Comment by viniciusgerevini** [comment]
Hello @boruok . Thanks for the detailed issue description. This behaviour is expected. To prevent groups from being exported you can use an exclusion pattern in their names.

The use-case for having groups exported is to allow merging frames to be used in Godot. This gives more freedom to use as many layers required in Aseprite, and still import them to Godot as just a few.

As an example, in Godot you might have a character composed of `head`, `upper_body` and `lower_body`. In Aseprite you can organise it like this:

```
head
  hair_
  face_
upper_body
  arms_
  torso_
lower_body
```
In this example, I'm using `_$` as exclusion pattern, stopping the inner layers from being exported. I can add or remove inner layers without impacting the resulting resources.
