### ISSUE TITLE
Update license

### ISSUE THREAD

**Issue by coppolaemilio** [viniciusgerevini/godot-aseprite-wizard#71]
You should probably update the year of the license to be 2022 (and if you make changes next moth, again to 2023)
https://github.com/viniciusgerevini/godot-aseprite-wizard/blob/master/LICENSE

Cheers!

**Comment by IPDramon** [comment]
Our you could just say "<Start date>-present".
Have seen that in some GitHub projects and even Godot engine itself uses it.

**Comment by coppolaemilio** [comment]
yeah, I commented this before knowing that it is really not necessary to update those every year. A very common misconception 😅

**Comment by viniciusgerevini** [comment]
Oh, thanks for info @coppolaemilio and @IPDramon . Sorry, I saw it and forgot to act on this one. It was never clear to me what  it was supposed to do with the dates. The the info is more than welcome. Cheers.
