### ISSUE TITLE
Layer Exclusion Pattern doesn't seem to be working

### ISSUE THREAD

**Issue by saint11** [viniciusgerevini/godot-aseprite-wizard#81]
Maybe I'm doing something wrong, but I tried many types of regex and nothing really seems to be working.
If this is working as intended, maybe adding some examples to the documentation could help!

**Comment by viniciusgerevini** [comment]
Hello @saint11 . Can you tell me which Godot version and operational system are you using so I can test it myself?

Can you also give me an example which pattern you are trying to use and the layer names?

I usually use `_$` as exclusion pattern and name my reference layers like `background_`. You can try this and let me know if it works for you. Just to rule out any bug in a specific version.

Your suggestion for examples is a good idea regardless. Thank you.

**Comment by saint11** [comment]
It's Godot Mono v4.0 on Windows. I'm using the auto-importer.
I tried the `_$` exclusion pattern and it also didn't work.
It seems that the JSON file created is also not being deleted.

Currently I hardcoded the addon to ignore layers that are not visible so I can use it, maybe there could be an option for ignoring hidden layers on the auto-importer too?

Thanks!

**Comment by saint11** [comment]
I figured it out, I found a workaround!

It is only taking in consideration the configuration set in the Aseprite Spritesheet tool window, it is currently ignoring the settings set in the Project Settings, which is where I was setting them.

I suggest either centralizing the config in one place or having the auto-importer use the config set in the Project Settings.

**Comment by viniciusgerevini** [comment]
Oh, definitely a bug. You are right, the auto-importer should use whatever is in the Project Settings by default in case no custom value is set. The settings in the tool window should only be used for the tool window.

I also didn´t realise the auto importer didn´t have the "only visibles" option. I'll put it there.

Thanks for reporting this.

**Comment by viniciusgerevini** [comment]
Oh, totally off topic, but I just realised I know your work @saint11. Thanks for making those great pixel art tutorials. And also as a side note, I love TowerFall haha.

**Comment by saint11** [comment]
Haha thank you! And thanks for making this extension, it's great!

**Comment by viniciusgerevini** [comment]
Fixes are already available in the  [releases](https://github.com/viniciusgerevini/godot-aseprite-wizard/releases) page and submitted to Godot Asset Lib. The Asset Lib has been a bit slow testing new submissions so I'm not sure when it's going to land there.

Notes:

- Auto-importer should use the default configuration from Project Settings.
- *.json file cleanup should happen on all import methods when option is enabled.
- The option to not include hidden layers was already available in the importer as "Only include visible layers" (It' s been working on my machines but let me know if you see any issue with that)

Thanks again for reporting this. :rocket:
