### ISSUE TITLE
Animation length is overwritten

### ISSUE THREAD

**Issue by Silvanuz** [viniciusgerevini/godot-aseprite-wizard#86]
First of all - Your aseprite wizard is a gamechanger. I love your Plugin!!! Thanks for your hard work ♥
And now my (small) issue.

My enemy has a death animation. This lasts 0.1 second in Aseprite.
![image](https://user-images.githubusercontent.com/36472149/229346775-f7586997-a7a5-4c0f-b270-414f383721ba.png)

But now I add effects like flashing red etc. in the animation player. Then the animation lasts maybe 0.3 seconds.
![image](https://user-images.githubusercontent.com/36472149/229346708-41137f64-5dcd-4192-9984-4d33c2da096b.png)

If I want to import the death animation with your tool again because I have changed something in the sprite, fortunately all my special effects remain. 
However, the animation length is overwritten again and lasts again 0.1 second. 
![image](https://user-images.githubusercontent.com/36472149/229346753-54362826-123b-4046-b669-01e7c195ebf5.png)
Then I have to manually restore the animation length.
Maybe a checkbox for "Do not overwrite already created animations values" is a good idea?

**Comment by viniciusgerevini** [comment]
Hello @Silvanuz thanks for reporting this. I had never thought about this scenario. Your checkbox suggestion seems to be the best way to go. I'll look into it.

**Comment by viniciusgerevini** [comment]
Implemented this in the latest version. Godot asset lib approval pending. In the meantime you can download the latest version from the version branch or releases page. Cheers.
