### ISSUE TITLE
Could not import aseprite file: output location does not exist

### ISSUE THREAD

**Issue by raulboo** [viniciusgerevini/godot-aseprite-wizard#9]
Hello! I'm trying to use this plugin, and when I manually import my .aseprite files through the SpriteSheet, it works fine by transforming them into resource files. But when the editor is trying to automatically import these .aseprite files, it shows following errors:

ERROR - Could not import aseprite file: output location does not exist
 editor/editor_file_system.cpp:1801 - Error importing 'res://characters/player/placeholder_toucan.aseprite'.
ERROR - Could not import aseprite file: output location does not exist
 editor/editor_file_system.cpp:1801 - Error importing 'res://characters/player/placeholder_toucan_flight.aseprite'.
ERROR - Could not import aseprite file: output location does not exist
 editor/editor_file_system.cpp:1801 - Error importing 'res://characters/player/placeholder_toucan_nonflight.aseprite'.

![image](https://user-images.githubusercontent.com/35705235/102992649-5c8a1c80-44fa-11eb-8ace-f56bfff996c5.png)
This is a screenshot from the files imported. As you can see, I was able to transform the .aseprite files into .res files, but the error message still shows. How can I fix that? Or maybe, how can I disable the automatic import of .aseprite files? Thank you

**Comment by viniciusgerevini** [comment]
Hello @raulboo. Thanks for notifying me about this issue. I'll have to investigate further to try to identify the root cause.

In the mean time, I'm releasing a new version with the option to disable the importer.
