### ISSUE TITLE
about Aseprite 1.3-rc4 new features: repeat in tag

### ISSUE THREAD

**Issue by chunhaqiushif** [viniciusgerevini/godot-aseprite-wizard#90]
![Snipaste_2023-07-01_17-44-58.jpg](https://s2.loli.net/2023/07/01/DNVQMOCZidWj87g.jpg)

Sorry to bother you. 

Recently, there has been a new beta version of Aseprite (it doesn't seem to be available on the official website yet, but I purchased Aseprite on Steam, and there is an option for this beta version). This new version includes a feature for animating repetitions, allowing a specific number of repetitions for animations within a tag. 
I would like to know if there are any subsequent plugin update for this new feature.
If not currently available, how can I temporarily modify the plugin so that I can obtain the value of 'Repeat'

About this in Aseprite API: 

Tag.repeats
```
local n = tag.repeats
tag.repeats = n
Gets or sets the number of times the tag is repeated/looped.
```
0 = Doesn't specify, plays infinite in UI, once on export, for ping-pong it plays once in each direction
1 = Plays once, for ping-pong it plays just in one direction
2 = Plays twice, for ping-pong it plays once in each direction, and once in reverse
n = Plays N times

**Comment by sandord** [comment]
~I looked into this recently and Aseprite doesn't seem to export this property (yet).~
Now that I've checked again, it seems to be there.

**Comment by viniciusgerevini** [comment]
Thanks for bringing this feature to my attention. I'm not working on this currently as I usually focus on features from the stable version, but that's definitely something I want to support in this plugin and RC is good enough for an implementation.

I haven´t looked into details on how this is exported so I can't really suggest a workaround for now. For cases like repeat infinite and don´t repeat you can use the loop tag pattern. Not exactly the same feature, but maybe it covers some of the cases.

I'll take a look at this and if it's like what I think it is I might have a new version with it this week.

Cheers

**Comment by viniciusgerevini** [comment]
Implemented this in the latest version. Godot asset lib approval pending. In the meantime you can download the latest version from the version branch or releases page. Cheers.

**Comment by chunhaqiushif** [comment]
Thank you very much!
